// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookmarks.sql

package database

import (
	"context"
	"time"
)

const createBookmark = `-- name: CreateBookmark :one
INSERT INTO bookmarks (guild_id, channel_id, author, preview, user_id, created_at)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, guild_id, channel_id, author, preview, user_id, created_at
`

type CreateBookmarkParams struct {
	GuildID   int64
	ChannelID int64
	Author    string
	Preview   string
	UserID    int64
	CreatedAt time.Time
}

func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) (Bookmark, error) {
	row := q.db.QueryRowContext(ctx, createBookmark,
		arg.GuildID,
		arg.ChannelID,
		arg.Author,
		arg.Preview,
		arg.UserID,
		arg.CreatedAt,
	)
	var i Bookmark
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.ChannelID,
		&i.Author,
		&i.Preview,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBookmarkForUserByID = `-- name: DeleteBookmarkForUserByID :exec
DELETE FROM bookmarks WHERE user_id = ? AND id = ?
`

type DeleteBookmarkForUserByIDParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) DeleteBookmarkForUserByID(ctx context.Context, arg DeleteBookmarkForUserByIDParams) error {
	_, err := q.db.ExecContext(ctx, deleteBookmarkForUserByID, arg.UserID, arg.ID)
	return err
}

const getBookmarksForUser = `-- name: GetBookmarksForUser :many
SELECT
    bookmarks.id,
    guilds.name AS guild_name,
    channels.name AS channel_name,
    bookmarks.author,
    bookmarks.preview,
    bookmarks.created_at
FROM bookmarks
JOIN guilds ON bookmarks.guild_id = guilds.id
JOIN channels ON bookmarks.channel_id = channels.id
WHERE bookmarks.user_id = ?
`

type GetBookmarksForUserRow struct {
	ID          int64
	GuildName   string
	ChannelName string
	Author      string
	Preview     string
	CreatedAt   time.Time
}

func (q *Queries) GetBookmarksForUser(ctx context.Context, userID int64) ([]GetBookmarksForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarksForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookmarksForUserRow
	for rows.Next() {
		var i GetBookmarksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildName,
			&i.ChannelName,
			&i.Author,
			&i.Preview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookmarksForUserByAuthor = `-- name: GetBookmarksForUserByAuthor :many
SELECT
    bookmarks.id,
    guilds.name AS guild_name,
    channels.name AS channel_name,
    bookmarks.author,
    bookmarks.preview,
    bookmarks.created_at
FROM bookmarks
JOIN guilds ON bookmarks.guild_id = guilds.id
JOIN channels ON bookmarks.channel_id = channels.id
WHERE bookmarks.user_id = ? AND bookmarks.author = ?
`

type GetBookmarksForUserByAuthorParams struct {
	UserID int64
	Author string
}

type GetBookmarksForUserByAuthorRow struct {
	ID          int64
	GuildName   string
	ChannelName string
	Author      string
	Preview     string
	CreatedAt   time.Time
}

func (q *Queries) GetBookmarksForUserByAuthor(ctx context.Context, arg GetBookmarksForUserByAuthorParams) ([]GetBookmarksForUserByAuthorRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarksForUserByAuthor, arg.UserID, arg.Author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookmarksForUserByAuthorRow
	for rows.Next() {
		var i GetBookmarksForUserByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildName,
			&i.ChannelName,
			&i.Author,
			&i.Preview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookmarksForUserByGuild = `-- name: GetBookmarksForUserByGuild :many
SELECT
    bookmarks.id,
    guilds.name AS guild_name,
    channels.name AS channel_name,
    bookmarks.author,
    bookmarks.preview,
    bookmarks.created_at
FROM bookmarks
JOIN guilds ON bookmarks.guild_id = guilds.id
JOIN channels ON bookmarks.channel_id = channels.id
WHERE bookmarks.user_id = ? AND bookmarks.guild_id = ?
`

type GetBookmarksForUserByGuildParams struct {
	UserID  int64
	GuildID int64
}

type GetBookmarksForUserByGuildRow struct {
	ID          int64
	GuildName   string
	ChannelName string
	Author      string
	Preview     string
	CreatedAt   time.Time
}

func (q *Queries) GetBookmarksForUserByGuild(ctx context.Context, arg GetBookmarksForUserByGuildParams) ([]GetBookmarksForUserByGuildRow, error) {
	rows, err := q.db.QueryContext(ctx, getBookmarksForUserByGuild, arg.UserID, arg.GuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBookmarksForUserByGuildRow
	for rows.Next() {
		var i GetBookmarksForUserByGuildRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildName,
			&i.ChannelName,
			&i.Author,
			&i.Preview,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetBookmarksForUser = `-- name: ResetBookmarksForUser :exec
DELETE FROM bookmarks WHERE user_id = ?
`

func (q *Queries) ResetBookmarksForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, resetBookmarksForUser, userID)
	return err
}

const resetBookmarksForUserByAuthor = `-- name: ResetBookmarksForUserByAuthor :exec
DELETE FROM bookmarks WHERE user_id = ? AND author = ?
`

type ResetBookmarksForUserByAuthorParams struct {
	UserID int64
	Author string
}

func (q *Queries) ResetBookmarksForUserByAuthor(ctx context.Context, arg ResetBookmarksForUserByAuthorParams) error {
	_, err := q.db.ExecContext(ctx, resetBookmarksForUserByAuthor, arg.UserID, arg.Author)
	return err
}

const resetBookmarksForUserByGuild = `-- name: ResetBookmarksForUserByGuild :exec
DELETE FROM bookmarks WHERE user_id = ? AND guild_id = ?
`

type ResetBookmarksForUserByGuildParams struct {
	UserID  int64
	GuildID int64
}

func (q *Queries) ResetBookmarksForUserByGuild(ctx context.Context, arg ResetBookmarksForUserByGuildParams) error {
	_, err := q.db.ExecContext(ctx, resetBookmarksForUserByGuild, arg.UserID, arg.GuildID)
	return err
}
