// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package database

import (
	"context"

	snowflake "github.com/disgoorg/snowflake/v2"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, external_id)
VALUES (
    ?,
    ?
)
RETURNING id, name, external_id
`

type CreateChannelParams struct {
	Name       string
	ExternalID snowflake.ID
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, arg.Name, arg.ExternalID)
	var i Channel
	err := row.Scan(&i.ID, &i.Name, &i.ExternalID)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, name, external_id FROM channels WHERE external_id = ?
`

func (q *Queries) GetChannel(ctx context.Context, externalID snowflake.ID) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, externalID)
	var i Channel
	err := row.Scan(&i.ID, &i.Name, &i.ExternalID)
	return i, err
}
