// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guilds.sql

package database

import (
	"context"
)

const createGuild = `-- name: CreateGuild :one
INSERT INTO guilds (name, external_id)
VALUES (
    ?,
    ?
)
RETURNING id, name, external_id
`

type CreateGuildParams struct {
	Name       string
	ExternalID int64
}

func (q *Queries) CreateGuild(ctx context.Context, arg CreateGuildParams) (Guild, error) {
	row := q.db.QueryRowContext(ctx, createGuild, arg.Name, arg.ExternalID)
	var i Guild
	err := row.Scan(&i.ID, &i.Name, &i.ExternalID)
	return i, err
}

const getGuild = `-- name: GetGuild :one
SELECT id, name, external_id FROM guilds WHERE external_id = ?
`

func (q *Queries) GetGuild(ctx context.Context, externalID int64) (Guild, error) {
	row := q.db.QueryRowContext(ctx, getGuild, externalID)
	var i Guild
	err := row.Scan(&i.ID, &i.Name, &i.ExternalID)
	return i, err
}
