// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	snowflake "github.com/disgoorg/snowflake/v2"
)

type Bookmark struct {
	ID        int64
	GuildID   int64
	ChannelID int64
	Author    string
	Preview   string
	UserID    snowflake.ID
	CreatedAt time.Time
}

type Channel struct {
	ID         int64
	Name       string
	ExternalID snowflake.ID
}

type Guild struct {
	ID         int64
	Name       string
	ExternalID snowflake.ID
}
