// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Bookmark struct {
	ID        int64
	GuildID   int64
	ChannelID int64
	Author    string
	Preview   string
	UserID    int64
	CreatedAt time.Time
}

type Channel struct {
	ID         int64
	Name       string
	ExternalID int64
}

type Guild struct {
	ID         int64
	Name       string
	ExternalID int64
}
